pull_request_rules:
  - name: Automatic merge on successful tests by PR from jona7o (Scala Steward)
    conditions:
      - author=jona7o
      - status-success~=test
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

