openapi: 3.0.0
info:
  title: "Bootstrap-Play2"
  description: "REST API"
  version: "0.0.1"
servers:
  - url: https://innfactory.de
    description: Production server (uses live data)
  - url: http://localhost:9000
    description: localhost
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: probes
    description: probe endpoints (health, liveness, readiness)
  - name: companies
    description: companies endpoints
  - name: locations
    description: locations endpoints
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []