version: '3.1'

services:
  db:
    container_name: bootstrapPlay2PG
    image: postgis/postgis:12-master
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - 5432:5432
    volumes:
      - ./postgis-volume/data:/var/lib/postgresql/data