name: Run Tests
on:
  push:
    branches:
      - 'feat/openapiYamlGen'
jobs:
  generateSwagger:
    name: Run swagger generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Compile project
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
        run: sbt compile || true
      - name: Run merge.sh
        run: .github/swagger/merge.sh
        shell: bash
      - name: Convert to yaml
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: 'output.swagger.json'
          from: 'json'
          to: 'yaml'
      - name: Update Pull Request with generated swagger file
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
          commit-message: 'feat: swagger'
          add-paths: 'output.swagger.yaml'
          branch: github.event.pull_request.title