name: Run Tests
on:
  push:
    branches:
      - 'feat/openapiYamlGen'
jobs:
  generateSwagger:
    name: Run swagger generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Compile project
        run: sbt compile || true
      - name: Run merge.sh
        run: .github/swagger/merge.sh
        shell: bash
      - name: Convert to yaml
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: 'openapi-merge.json'
          from: 'json'
          to: 'yaml'
      - name: Print json2yaml result
        run: echo "${{ steps.json2yaml.outputs.data }}"
