name: Run Tests
on:
  pull_request:
    branches: [ master ]
jobs:
  generateSwagger:
    name: Run swagger generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Compile project
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
        run: sbt compile || true
      - name: Run merge.sh
        run: .github/swagger/merge.sh
        shell: bash
      - name: Convert to yaml
        uses: fabasoad/yaml-json-xml-converter-action@v1.0.14
        id: json2yaml
        with:
          path: 'output.swagger.json'
          from: 'json'
          to: 'yaml'
      - name: Write converted yaml into file
        run: echo '${{ steps.json2yaml.outputs.data }}' > 'api.swagger.yaml'
      - name: Update Pull Request with generated swagger file
        uses: EndBug/add-and-commit@v9
        with:
          message: 'feat: update api.swagger.yaml'
          add: 'api.swagger.yaml'